MVC/Controllers/ClassController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BLL.Controllers.Bases;
using BLL.Services.Bases;
using BLL.Models;
using BLL.DAL;
using BLL.Services;

// Generated from Custom Template.

namespace MVC.Controllers
{
    public class ClassController : MvcController
    {
        // Service injections:
        private readonly IClassService _classService;

        /* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. */
        //private readonly IService<{Entity}, {Entity}Model> _{Entity}Service;

        public ClassController(
            IClassService classService

            /* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. */
            //, Service<{Entity}, {Entity}Model> {Entity}Service
        )
        {
            _classService = classService;

            /* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. */
            //_{Entity}Service = {Entity}Service;
        }

        // GET: Classes
        public IActionResult Index()
        {
            // Get collection service logic:
            var list = _classService.Query().ToList();
            return View(list);
        }

        // GET: Classes/Details/5
        public IActionResult Details(int id)
        {
            // Get item service logic:
            var item = _classService.Query().SingleOrDefault(q => q.Record.Id == id);
            return View(item);
        }

        protected void SetViewData()
        {
            // Related items service logic to set ViewData (Record.Id and Name parameters may need to be changed in the SelectList constructor according to the model):
            
            /* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. */
            //ViewBag.{Entity}Ids = new MultiSelectList(_{Entity}Service.Query().ToList(), "Record.Id", "Name");
        }

        // GET: Classes/Create
        public IActionResult Create()
        {
            SetViewData();
            return View();
        }

        // POST: Classes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ClassModel @class)
        {
            if (ModelState.IsValid)
            {
                // Insert item service logic:
                var result = _classService.Create(@class.Record);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Details), new { id = @class.Record.Id });
                }
                ModelState.AddModelError("", result.Message);
            }
            SetViewData();
            return View(@class);
        }

        // GET: Classes/Edit/5
        public IActionResult Edit(int id)
        {
            // Get item to edit service logic:
            var item = _classService.Query().SingleOrDefault(q => q.Record.Id == id);
            SetViewData();
            return View(item);
        }

        // POST: Classes/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ClassModel @class)
        {
            if (ModelState.IsValid)
            {
                // Update item service logic:
                var result = _classService.Update(@class.Record);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Details), new { id = @class.Record.Id });
                }
                ModelState.AddModelError("", result.Message);
            }
            SetViewData();
            return View(@class);
        }

        // GET: Classes/Delete/5
        public IActionResult Delete(int id)
        {
            // Get item to delete service logic:
            var item = _classService.Query().SingleOrDefault(q => q.Record.Id == id);
            return View(item);
        }

        // POST: Classes/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            // Delete item service logic:
            var result = _classService.Delete(id);
            TempData["Message"] = result.Message;
            return RedirectToAction(nameof(Index));
        }
	}
}

MVC/Views/Class/Create.cshtml
@model ClassModel

@* Generated from Custom Template. *@
@* Model namespace using directive should be added to _ViewImports.cshtml. *@

@{
    var containerDivClass = "container";
    var dateTimePickerClass = "datetimepicker";
}
@{
    ViewData["Title"] = "Class Create";
}

<div class="@containerDivClass">
    <h3>@ViewData["Title"]</h3>
    <hr />
</div>

<div class="@containerDivClass">
    @if (TempData["Message"] is not null)
    {
    <p class="text-danger">
        @TempData["Message"]
    </p>
    }
    <form asp-action="Create" autocomplete="off">
		@Html.AntiForgeryToken()
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row mb-3">
            <label asp-for="Name" class="col-2 col-form-label fw-bold"></label>
			<div class="col-10">
			    <input asp-for="Record.Name" class="form-control" />
				<span asp-validation-for="Record.Name" class="text-danger"></span>
			</div>
        </div>

@* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. *@
        @*
        <div class="row mb-3">
            <label asp-for="{Entity}Ids" class="col-2 col-form-label fw-bold"></label>
	        <div class="col-10">
		        <select multiple asp-for="{Entity}Ids" class="form-select" asp-items="ViewBag.{Entity}Ids"></select>
		        <span asp-validation-for="{Entity}Ids" class="text-danger"></span>
	        </div>
        </div>
        *@

        <hr />  
        <div class="row mb-3">
			<div class="offset-2 col-10">
                <button type="submit" class="btn btn-primary">Save</button>
				&nbsp;&nbsp;
                <button type="reset" class="btn btn-outline-primary">Reset</button>
				&nbsp;&nbsp;
				<a asp-action="Index">Back to List</a>
			</div>
        </div>
    </form>
</div>  

MVC/Views/Class/Delete.cshtml
@model ClassModel

@* Generated from Custom Template. *@
@* Model namespace using directive should be added to _ViewImports.cshtml. *@

@{
    var containerDivClass = "container";
}
@{
    ViewData["Title"] = "Class Delete";
}

<div class="@containerDivClass">
    <h3>@ViewData["Title"]</h3>
    <hr />
</div>

@if (Model is not null)
{
<div class="@containerDivClass">
    @if (TempData["Message"] is not null)
    {
    <p class="text-danger">
        @TempData["Message"]
    </p>
    }
    <h3 class="text-danger">Are you sure you want to delete?</h3>
    <hr />
    <div class="row mb-3">
        <div class="col-2 fw-bold">
            @Html.DisplayNameFor(model => model.Name)
        </div>
        <div class="col-10">
            @Html.DisplayFor(model => model.Name)
        </div>
    </div>

@* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. *@
    @*
    <div class="row mb-3">
        <div class="col-2 fw-bold">
            <b>@Html.DisplayNameFor(model => model.{Entity}s)</b>
        </div>
        <div class="col-10">
            @Html.Raw(Model.{Entity}s)
        </div>
    </div>
    *@

    <hr />
    <form asp-action="Delete">
	    @Html.AntiForgeryToken()
        <input type="hidden" asp-for="Record.Id" />
        <input type="submit" value="Yes" class="btn btn-danger" />&nbsp;&nbsp;
        <a asp-action="Index" class="btn btn-outline-danger">No</a>
    </form>
</div>
}

MVC/Views/Class/Details.cshtml
@model ClassModel

@* Generated from Custom Template. *@
@* Model namespace using directive should be added to _ViewImports.cshtml. *@

@{
    var containerDivClass = "container";
}
@{
    ViewData["Title"] = "Class Details";
}

<div class="@containerDivClass">
    <h3>@ViewData["Title"]</h3>
    <hr />
</div>

@if (Model is not null)
{
<div class="@containerDivClass">
    @if (TempData["Message"] is not null)
    {
    <p class="text-danger">
        @TempData["Message"]
    </p>
    }
    <div class="row mb-3">
        <div class="col-2 fw-bold">
            @Html.DisplayNameFor(model => model.Name)
        </div>
        <div class="col-10">
            @Html.DisplayFor(model => model.Name)
        </div>
    </div>

@* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. *@
    @*
    <div class="row mb-3">
        <div class="col-2 fw-bold">
            <b>@Html.DisplayNameFor(model => model.{Entity}s)</b>
        </div>
        <div class="col-10">
            @Html.Raw(Model.{Entity}s)
        </div>
    </div>
    *@

    <hr /> 
    <a asp-action="Edit" asp-route-id="@Model.Record.Id">Edit</a>&nbsp;|&nbsp;
    <a asp-action="Delete" asp-route-id="@Model.Record.Id">Delete</a>&nbsp;|&nbsp;
    <a asp-action="Index">Back to List</a>
</div>
}

MVC/Views/Class/Edit.cshtml
@model ClassModel

@* Generated from Custom Template. *@
@* Model namespace using directive should be added to _ViewImports.cshtml. *@

@{
    var containerDivClass = "container";
    var dateTimePickerClass = "datetimepicker";
}
@{
    ViewData["Title"] = "Class Edit";
}

<div class="@containerDivClass">
    <h3>@ViewData["Title"]</h3>
    <hr />
</div>

@if (Model is not null)
{
<div class="@containerDivClass">
    @if (TempData["Message"] is not null)
    {
    <p class="text-danger">
        @TempData["Message"]
    </p>
    }
    <form asp-action="Edit" autocomplete="off">
	    @Html.AntiForgeryToken()
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Record.Id" />
        <div class="row mb-3">
            <label asp-for="Name" class="col-2 col-form-label fw-bold"></label>
	        <div class="col-10">
	            <input asp-for="Record.Name" class="form-control" />
		        <span asp-validation-for="Record.Name" class="text-danger"></span>
	        </div>
        </div>

@* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. *@
        @*
        <div class="row mb-3">
            <label asp-for="{Entity}Ids" class="col-2 col-form-label fw-bold"></label>
	        <div class="col-10">
		        <select multiple asp-for="{Entity}Ids" class="form-select" asp-items="ViewBag.{Entity}Ids"></select>
		        <span asp-validation-for="{Entity}Ids" class="text-danger"></span>
	        </div>
        </div>
        *@

        <hr />
        <div class="row mb-3">
	        <div class="offset-2 col-10">
                <button type="submit" class="btn btn-primary">Save</button>
		        &nbsp;&nbsp;
                <button type="reset" class="btn btn-outline-primary">Reset</button>
		        &nbsp;&nbsp;
                <a asp-action="Delete" asp-route-id="@Model.Record.Id">Delete</a>
                &nbsp;&nbsp;
		        <a asp-action="Index">Back to List</a>
	        </div>
        </div>
    </form>
</div>
}

MVC/Views/Class/Index.cshtml
@model IEnumerable<ClassModel>

@* Generated from Custom Template. *@
@* Model namespace using directive should be added to _ViewImports.cshtml. *@

@{
    var containerDivClass = "container";
}
@{
    ViewData["Title"] = "Class List";
}

<div class="@containerDivClass">
    <h3>@ViewData["Title"]</h3>
    <hr />
</div>

@if (Model is not null)
{
    <form asp-action="Index" autocomplete="off">
        <div class="@containerDivClass">
            <div class="row">
                <div class="col-12 text-danger">
                    @TempData["Message"]
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-10 text-success">
                    @Model.Count() record(s) found.
                </div>
                <div class="col-2 text-end">
                    <a asp-action="Create">Create</a>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead class="table-secondary">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
		            @foreach (var item in Model) {
				        <tr>
					        <td>
						        @Html.DisplayFor(modelItem => item.Name)
					        </td>
					        <td class="text-end w-25">

						        <a asp-action="Details" asp-controller="Class" asp-route-id="@item.Record.Id">Details</a>&nbsp;|&nbsp;
                           
                                <a asp-action="Edit" asp-route-id="@item.Record.Id">Edit</a>&nbsp;|&nbsp;
                             
                                <a asp-action="Delete" asp-route-id="@item.Record.Id">Delete</a>
					        </td>
				        </tr>
		            }
                </tbody>
            </table>
        </div>
    </form>
}